/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SecondaryClassRouteImport } from './routes/secondary-class'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MapRouteImport } from './routes/map'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppearanceRouteImport } from './routes/appearance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemIndexRouteImport } from './routes/system.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondaryClassRoute = SecondaryClassRouteImport.update({
  id: '/secondary-class',
  path: '/secondary-class',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppearanceRoute = AppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appearance': typeof AppearanceRoute
  '/auth': typeof AuthRoute
  '/career': typeof CareerRoute
  '/claims': typeof ClaimsRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/evaluations': typeof EvaluationsRoute
  '/fleet': typeof FleetRoute
  '/manager': typeof ManagerRoute
  '/map': typeof MapRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/secondary-class': typeof SecondaryClassRoute
  '/system': typeof SystemRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/system/': typeof SystemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appearance': typeof AppearanceRoute
  '/auth': typeof AuthRoute
  '/career': typeof CareerRoute
  '/claims': typeof ClaimsRoute
  '/evaluations': typeof EvaluationsRoute
  '/fleet': typeof FleetRoute
  '/manager': typeof ManagerRoute
  '/map': typeof MapRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/secondary-class': typeof SecondaryClassRoute
  '/collections': typeof CollectionsIndexRoute
  '/system': typeof SystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appearance': typeof AppearanceRoute
  '/auth': typeof AuthRoute
  '/career': typeof CareerRoute
  '/claims': typeof ClaimsRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/evaluations': typeof EvaluationsRoute
  '/fleet': typeof FleetRoute
  '/manager': typeof ManagerRoute
  '/map': typeof MapRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/secondary-class': typeof SecondaryClassRoute
  '/system': typeof SystemRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/system/': typeof SystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/appearance'
    | '/auth'
    | '/career'
    | '/claims'
    | '/collections'
    | '/evaluations'
    | '/fleet'
    | '/manager'
    | '/map'
    | '/performance'
    | '/profile'
    | '/promotions'
    | '/secondary-class'
    | '/system'
    | '/collections/'
    | '/system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/appearance'
    | '/auth'
    | '/career'
    | '/claims'
    | '/evaluations'
    | '/fleet'
    | '/manager'
    | '/map'
    | '/performance'
    | '/profile'
    | '/promotions'
    | '/secondary-class'
    | '/collections'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/appearance'
    | '/auth'
    | '/career'
    | '/claims'
    | '/collections'
    | '/evaluations'
    | '/fleet'
    | '/manager'
    | '/map'
    | '/performance'
    | '/profile'
    | '/promotions'
    | '/secondary-class'
    | '/system'
    | '/collections/'
    | '/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppearanceRoute: typeof AppearanceRoute
  AuthRoute: typeof AuthRoute
  CareerRoute: typeof CareerRoute
  ClaimsRoute: typeof ClaimsRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  EvaluationsRoute: typeof EvaluationsRoute
  FleetRoute: typeof FleetRoute
  ManagerRoute: typeof ManagerRoute
  MapRoute: typeof MapRoute
  PerformanceRoute: typeof PerformanceRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  SecondaryClassRoute: typeof SecondaryClassRoute
  SystemRoute: typeof SystemRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secondary-class': {
      id: '/secondary-class'
      path: '/secondary-class'
      fullPath: '/secondary-class'
      preLoaderRoute: typeof SecondaryClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appearance': {
      id: '/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof SystemRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface SystemRouteChildren {
  SystemIndexRoute: typeof SystemIndexRoute
}

const SystemRouteChildren: SystemRouteChildren = {
  SystemIndexRoute: SystemIndexRoute,
}

const SystemRouteWithChildren =
  SystemRoute._addFileChildren(SystemRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppearanceRoute: AppearanceRoute,
  AuthRoute: AuthRoute,
  CareerRoute: CareerRoute,
  ClaimsRoute: ClaimsRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  EvaluationsRoute: EvaluationsRoute,
  FleetRoute: FleetRoute,
  ManagerRoute: ManagerRoute,
  MapRoute: MapRoute,
  PerformanceRoute: PerformanceRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  SecondaryClassRoute: SecondaryClassRoute,
  SystemRoute: SystemRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
